easy_admin:
    site_name: 'PRM'
    entities:
        Activacion:
            class: WE\ReportBundle\Entity\Activacion
        Agencia:
            class: WE\ReportBundle\Entity\Agencia    
        ActivacionComentario:
            class: WE\ReportBundle\Entity\ActivacionComentario
        ActivacionTipo:
            class: WE\ReportBundle\Entity\ActivacionTipo
        ActivacionTipoMaterial:
            class: WE\ReportBundle\Entity\ActivacionTipoMaterial   
        Status:
            class: WE\ReportBundle\Entity\ActivacionStatus     
        CDC:
            class: WE\ReportBundle\Entity\CDC
        CDCType:
            class: WE\ReportBundle\Entity\CDCType 
        Instrumento:
            class: WE\ReportBundle\Entity\Instrumento 
        Reporte:
            class: WE\ReportBundle\Entity\Reporte    
        Marca:
            class: WE\ReportBundle\Entity\Marca 
        Plaza:
            class: WE\ReportBundle\Entity\Plaza
        Region:
            class: WE\ReportBundle\Entity\Region         
        Proyecto:
            class: WE\ReportBundle\Entity\Proyecto
        TipoColumna:
            class: WE\ReportBundle\Entity\TipoColumna
        Usuario:
            class: WE\ReportBundle\Entity\Usuario  
        Notificacion:
            class: WE\ReportBundle\Entity\Notificacion              