# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    WE\ReportBundle\Form\UsuarioActivacionProductorType:
        arguments: ['@security.token_storage']
        tags: [form.type]

    WE\ReportBundle\Form\ActivacionType:
        arguments: ['@security.token_storage']
        tags: [form.type]
        
    WE\ReportBundle\Form\UsuarioActivacionSupervisorType:
        arguments: ['@security.token_storage']
        tags: [form.type]
  
    proyect_validator:
        class: WE\ReportBundle\Proyect\ProyectValidator    
        
    status_generator:
        class: WE\ReportBundle\Notification\StatusGenerator
        
    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }
    _defaults:
        # automatically injects dependencies in your services
        autowire: true
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true
        # this means you cannot fetch services directly from the container via $container->get()
        # if you need to do this, you can override this setting on individual services
        public: false

    # makes classes in src/AppBundle available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
