<?php

namespace WE\ReportBundle\Entity\Repository;

/**
 * UsuarioActivacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsuarioActivacionRepository extends \Doctrine\ORM\EntityRepository
{
}
