<?php

namespace WE\ReportBundle\Repository;

/**
 * ActivacionLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActivacionLogRepository extends \Doctrine\ORM\EntityRepository
{
}
