<?php

namespace WE\ReportBundle\Repository;

/**
 * ActivacionTipoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActivacionTipoRepository extends \Doctrine\ORM\EntityRepository
{
}
