<?php

namespace WE\ReportBundle\Repository;

/**
 * ActivacionComentarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActivacionComentarioRepository extends \Doctrine\ORM\EntityRepository {

    public function findByComentariosMood($activaciones) {


        $query = $this->createQueryBuilder('c')
                ->select('COUNT(c.rating) as total,c.rating as label')
                ->andWhere('c.rating IS NOT NULL')
                ->andWhere('c.activacion IN (:activaciones)')
                ->andWhere('c.tipo = :tipo')
                ->orderBy('c.rating', 'DESC')
                ->setParameter('tipo', "Comentario")
                ->setParameter('activaciones', $activaciones)
                ->groupBy('c.rating')
        ;
        return $query->getQuery()->execute();
    }

    public function findByComentariosAgencia($activaciones) {

        $query = $this->createQueryBuilder('c')
                ->andWhere('c.rating IS NULL')
                ->andWhere('c.activacion IN (:activaciones)')
                ->andWhere('c.tipo = :tipo')
                ->setParameter('tipo', "Comentario")
                ->setParameter('activaciones', $activaciones)
                ->groupBy('c.rating')
                ->orderBy('c.fecha','ASC')
        ;

        return $query->getQuery()->setMaxResults(1)->execute();
    }

}
