<?php

namespace WE\ReportBundle\Repository;

/**
 * ActivacionTipoMaterialRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActivacionTipoMaterialRepository extends \Doctrine\ORM\EntityRepository
{
}
