<?php

namespace WE\ReportBundle\Repository;

/**
 * ActivacionTipoTalentoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActivacionTipoTalentoRepository extends \Doctrine\ORM\EntityRepository
{
}
