<?php

namespace WE\ReportBundle\Repository;

/**
 * ActivacionStatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActivacionStatusRepository extends \Doctrine\ORM\EntityRepository
{
}
