<?php

namespace WE\ReportBundle\Repository;

/**
 * MarcaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MarcaRepository extends \Doctrine\ORM\EntityRepository {

    public function findByData($user = null, $max = 10) {

        return $this->createQueryBuilder('m')
                        ->join('m.proyectos', 'pr')
                        ->join('m.instrumentos', 'i')
                        ->setMaxResults($max)
                        ->getQuery()
                        ->execute();
    }

}
