<?php

namespace WE\ReportBundle\Repository;

/**
 * ProyectoAsignacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProyectoAsignacionRepository extends \Doctrine\ORM\EntityRepository
{
}
